"""
Generate Mechanical APDL input decks from config.

The material card is from config.NITINOL, so the numbers in Ansys can't drift from 
the sourced values in the repo.

Ansys superelasticity (TB,SMA,...,SUPE) takes six Auricchio constants:

    C1 sigma_s^AS   Start of the austenite -> martensite transformation (loading)
    C2 sigma_f^AS   Finish of it
    C3 sigma_s^SA   Start of the reverse transformation (unloading)
    C4 sigma_f^SA   Finish of it
    C5 epsilon_L    Maximum transformation strain
    C6 alpha        Tension/compression asymmetry

`alpha` is derived from the compressive transformation stress:
    alpha = (sigma_CLS - sigma_LS) / (sigma_CLS + sigma_LS)

The six-constant model carries one elastic modulus (austenite, via MP,EX). Our
E_martensite = 23500 MPa is therefore not used by this material card.
"""

import config

def alpha():
    """Tension/compression asymmetry parameter for the Auricchio model."""
    t = config.NITINOL['sigma_start_loading_MPa']
    c = config.NITINOL['sigma_start_loading_compression_MPa']
    return (c - t) / (c + t)

def material_card(mat=1):
    """APDL lines defining the superelastic nitinol material."""
    n = config.NITINOL
    return f"""! ---- Nitinol, superelastic (Auricchio). Generated from config.NITINOL.
! Source: {config.SOURCES['NITINOL'][:96]}...
MP,EX,{mat},{n['E_austenite_MPa']}          ! austenite Young's modulus, MPa
MP,PRXY,{mat},{n['poisson_austenite']}
MP,DENS,{mat},{n['density_tonne_per_mm3']}  ! tonne/mm^3 (mm-t-s system)
TB,SMA,{mat},,,SUPE
TBDATA,1,{n['sigma_start_loading_MPa']},{n['sigma_finish_loading_MPa']},\
{n['sigma_start_unloading_MPa']},{n['sigma_finish_unloading_MPa']},\
{n['eps_transformation']},{alpha():.6f}"""

def single_element_spike(strain=0.05, substeps=60, out_stem='s0_2_spike_sma'):
    """
    One element, tension load-unload, dumping stress-strain to CSV.

    Displacement control, not force control - a superelastic plateau is flat in stress, so
    a force-driven test jumps straight across it and shows no hysteresis at all.
    """
    return f"""! =====================================================================
! Nitinol superelastic hysteresis, single element
! Generated by sim3d/apdl.py.
! UNITS: {config.UNITS_BANNER}
! Expect: loading plateau near {config.NITINOL['sigma_start_loading_MPa']:.0f}-\
{config.NITINOL['sigma_finish_loading_MPa']:.0f} MPa,
!         unloading plateau near {config.NITINOL['sigma_start_unloading_MPa']:.0f}-\
{config.NITINOL['sigma_finish_unloading_MPa']:.0f} MPa,
!         recoverable strain to ~{config.NITINOL['eps_transformation'] * 100:.1f} %,
!         and a closed loop returning to ~zero strain at zero stress.
! =====================================================================
FINISH
/CLEAR,NOSTART
/FILNAME,{out_stem},1          ! Self-naming within session
/PREP7
/TITLE, S0.2 spike - nitinol superelasticity

ET,1,SOLID185                  ! 3D 8-node structural solid

{material_card()}

! ---- One 1 mm cube, so strain = displacement and stress = force
BLOCK,0,1,0,1,0,1
ESIZE,1
VMESH,ALL

! ---- Symmetry on three faces: uniaxial, free to contract laterally (Poisson)
NSEL,S,LOC,X,0
D,ALL,UX,0
NSEL,S,LOC,Y,0
D,ALL,UY,0
NSEL,S,LOC,Z,0
D,ALL,UZ,0
NSEL,ALL

! ---- Find the loaded node by location, not by assuming a node number
NSEL,S,LOC,Z,1
*GET,NTOP,NODE,0,NUM,MIN
NSEL,ALL
FINISH

/SOLU
ANTYPE,STATIC
NLGEOM,ON                      ! ~5 % strain is past the small-strain assumption
OUTRES,ALL,ALL
AUTOTS,ON

! ---- Load step 1: stretch to {strain * 100:.1f} %
NSEL,S,LOC,Z,1
D,ALL,UZ,{strain}
NSEL,ALL
NSUBST,{substeps},{substeps * 4},{substeps}
TIME,1
SOLVE

! ---- Load step 2: release back to zero
NSEL,S,LOC,Z,1
D,ALL,UZ,0
NSEL,ALL
NSUBST,{substeps},{substeps * 4},{substeps}
TIME,2
SOLVE
FINISH

! ---- Dump stress-strain history
! Strain is taken as UZ directly: the cube is 1 mm tall, so displacement is strain, and
! that sidesteps any ambiguity about which strain item Ansys reports under NLGEOM.
/POST26
NUMVAR,10
NSOL,2,NTOP,U,Z,UZ
ESOL,3,1,NTOP,S,Z,SZ
/OUTPUT,{out_stem},txt
PRVAR,2,3
/OUTPUT
! whitespace table, not true CSV - parse with sim3d.apdl.read_prvar()
FINISH
"""

def read_prvar(path):
    """
    Parse an APDL PRVAR table into (time, uz, sz) arrays.

    PRVAR writes a whitespace table with repeated headers and page breaks, not CSV, so this
    keeps only lines that are entirely numeric.
    """
    import numpy as np

    rows = []
    for line in open(path, encoding='utf-8', errors='ignore'):
        parts = line.split()
        if len(parts) < 3:
            continue
        try:
            rows.append([float(x) for x in parts[:3]])
        except ValueError:
            continue
    if not rows:
        raise ValueError(f'No numeric rows found in {path}')
    data = np.array(rows)
    return data[:, 0], data[:, 1], data[:, 2]

def bending_verification(n_through=4, length_mm=5.0, width_mm=0.15, thick_mm=0.22, tip_load_N=0.01, out_stem='s5_2_bending'):
    """
    Cantilever beam vs Euler-Bernoulli - does SOLID185 capture bending?

    Our struts are thin and bending-dominated, and we mesh only `n_through` elements through
    the thickness. If the element formulation shear-locks, the model comes out stiff and 
    every strain it reports is wrong.

    Tip deflection for an end-loaded cantilever is PL^3/(3EI), I = w*t^3/12.
    """
    E = config.NITINOL['E_austenite_MPa']
    nu = config.NITINOL['poisson_austenite']
    I = width_mm * thick_mm ** 3 / 12.0
    analytic = tip_load_N * length_mm ** 3 / (3.0 * E * I)
    n_len = max(10, int(round(length_mm / thick_mm)) * 2)

    return f"""! =====================================================================
! SOLID185 enhanced strain vs Euler-Bernoulli bending
! Generated by sim3d/apdl.py.
! UNITS: {config.UNITS_BANNER}
! Cantilever {length_mm} x {width_mm} x {thick_mm} mm, tip load {tip_load_N} N
! I = {I:.6e} mm^4, analytic tip deflection = PL^3/3EI = {analytic:.6e} mm
! A locking element reports less deflection than this.
! =====================================================================
FINISH
/CLEAR,NOSTART
/FILNAME,{out_stem},1          ! Self-naming within session
/PREP7
/TITLE, Bending verification

ET,1,SOLID185
KEYOPT,1,2,2                   ! Enhanced strain, the setting under test
MP,EX,1,{E}
MP,PRXY,1,{nu}

BLOCK,0,{length_mm},0,{width_mm},0,{thick_mm}
LSEL,S,LOC,X,{length_mm / 2}
LESIZE,ALL,,,{n_len}
LSEL,S,LOC,Y,{width_mm / 2}
LESIZE,ALL,,,2
LSEL,S,LOC,Z,{thick_mm / 2}
LESIZE,ALL,,,{n_through}
LSEL,ALL
MSHAPE,0,3D                    ! Hexahedra
MSHKEY,1                       ! Mapped - a block with all divisions set meshes reliably;
VMESH,ALL                      ! VSWEEP can refuse to pick source/target and leave 0 elements
*GET,NELEM,ELEM,0,COUNT
/COM, ---- Meshed NELEM elements (0 means the mesh failed and nothing below is valid)
*STATUS,NELEM

NSEL,S,LOC,X,0
D,ALL,ALL,0                    ! Built-in root
NSEL,S,LOC,X,{length_mm}
*GET,NTIP,NODE,0,NUM,MIN
CM,TIPNODES,NODE
*GET,NT,NODE,0,COUNT
FPERNODE = {tip_load_N}/NT     ! Evaluate first; an inline expression in F is fragile
F,ALL,FZ,FPERNODE
NSEL,ALL
FINISH

/SOLU
ANTYPE,STATIC
SOLVE
FINISH

/POST1
SET,LAST
*GET,UZTIP,NODE,NTIP,U,Z
ANALYTIC = {analytic:.9e}
RATIO = UZTIP/ANALYTIC
/OUTPUT,{out_stem},txt
*STATUS,NELEM
*STATUS,UZTIP
*STATUS,ANALYTIC
*STATUS,RATIO
/OUTPUT
FINISH
"""

def bending_strain(n_through=4, length_mm=5.0, width_mm=0.15, thick_mm=0.22, tip_load_N=0.01, out_stem='s5_3_strain4'):
    """
    Where is bending strain actually sampled, and how many layers does eps_a_max need?

    Evaluated at mid-span, not the root: the moment there is P*L/2 and the section is ~11
    thicknesses from the clamp, so the St. Venant disturbance has decayed and the
    Euler-Bernoulli strain is clean.

    Reports, against the closed form eps = M*c/(E*I):
      ECENTR  max centroidal element strain  (what S5.3 Part 1 used: ETABLE,EPTO,1)
      ENODAL  max nodal strain on the top surface (extrapolated to the surface)
    """
    E = config.NITINOL['E_austenite_MPa']
    nu = config.NITINOL['poisson_austenite']
    I = width_mm * thick_mm ** 3 / 12.0
    n_len = max(10, int(round(length_mm / thick_mm)) * 2)

    # Mid-span section: moment there, surface fiber distance, closed-form surface strain.
    x_mid = length_mm / 2.0
    moment = tip_load_N * (length_mm - x_mid)
    c = thick_mm / 2.0
    eps_surf = moment * c / (E * I)
    # A centroid-sampled outer element sits at this fraction of the surface fiber distance.
    frac = (1.0 - 1.0 / n_through) if n_through > 0 else 0.0
    dx = length_mm / n_len

    return f"""! =====================================================================
! Where bending strain is sampled: element centroid vs surface node
! Generated by sim3d/apdl.py.
! UNITS: {config.UNITS_BANNER}
! Cantilever {length_mm} x {width_mm} x {thick_mm} mm, tip load {tip_load_N} N
! {n_through} element(s) through the thickness.
! Mid-span x={x_mid}: M = {moment:.6e} N-mm, c = {c}, I = {I:.6e} mm^4
! Closed-form SURFACE strain eps = M*c/(E*I) = {eps_surf:.6e}
! Predicted centroid undersampling for the outer layer: {frac:.4f} of the surface value.
! =====================================================================
FINISH
/CLEAR,NOSTART
/FILNAME,{out_stem},1          ! Self-naming within session
/PREP7
/TITLE, Bending strain sampling

ET,1,SOLID185
KEYOPT,1,2,2                   ! Enhanced strain, same setting as the real model
MP,EX,1,{E}
MP,PRXY,1,{nu}

BLOCK,0,{length_mm},0,{width_mm},0,{thick_mm}
LSEL,S,LOC,X,{length_mm / 2}
LESIZE,ALL,,,{n_len}
LSEL,S,LOC,Y,{width_mm / 2}
LESIZE,ALL,,,2
LSEL,S,LOC,Z,{thick_mm / 2}
LESIZE,ALL,,,{n_through}
LSEL,ALL
MSHAPE,0,3D
MSHKEY,1
VMESH,ALL
*GET,NELEM,ELEM,0,COUNT
/COM, ---- Meshed NELEM elements (0 means the mesh failed and nothing below is valid)
*STATUS,NELEM

NSEL,S,LOC,X,0
D,ALL,ALL,0                    ! Built-in root
NSEL,S,LOC,X,{length_mm}
CM,TIPNODES,NODE
*GET,NT,NODE,0,COUNT
FPERNODE = {tip_load_N}/NT
F,ALL,FZ,FPERNODE
NSEL,ALL
FINISH

/SOLU
ANTYPE,STATIC
SOLVE
FINISH

/POST1
SET,LAST
EPSSURF = {eps_surf:.9e}

! ---- Centroidal element strain at mid-span (the S5.3 Part 1 method).
ESEL,S,CENT,X,{x_mid - dx:.6f},{x_mid + dx:.6f}
*GET,NESEL,ELEM,0,COUNT
ETABLE,EX1,EPTO,1
ESORT,ETAB,EX1,,1
*GET,ECENTR,SORT,,MAX
ESEL,ALL

! ---- Nodal strain on the TOP SURFACE at mid-span (extrapolated to the surface).
NSEL,S,LOC,X,{x_mid}
NSEL,R,LOC,Z,{thick_mm}
*GET,NNSEL,NODE,0,COUNT
NSORT,EPTO,X,,1
*GET,ENODAL,SORT,,MAX
NSEL,ALL

RCENTR = ECENTR/EPSSURF
RNODAL = ENODAL/EPSSURF

/OUTPUT,{out_stem},txt
*STATUS,NELEM
*STATUS,NESEL
*STATUS,NNSEL
*STATUS,EPSSURF
*STATUS,ECENTR
*STATUS,ENODAL
*STATUS,RCENTR
*STATUS,RNODAL
/OUTPUT
FINISH
"""

def spike_a_model(mesh='spikeA_sector', deck_dir=None, strain=0.002, out_stem='s5_2_model'):
    """
    Mesh + superelastic material + a minimal solve.

    This proves that the material card binds to the imported elements, the mm-t-s unit
    system is consistent end to end, the enhanced-strain formulation is accepted, and the
    solver reaches equilibrium on the real geometry. A small axial stretch is enough for all
    of that, and staying below the transformation stress (config.NITINOL['sigma_start_loading_MPa'] MPa)
    keeps the response elastic.
    """
    deck_dir = (config.PROJECT_ROOT / 'sim3d' / 'decks') if deck_dir is None else deck_dir
    n = config.NITINOL
    expected = n['E_austenite_MPa'] * strain

    return f"""! =====================================================================
! Material applied to the Spike A mesh, minimal solve
! Generated by sim3d/apdl.py.
! UNITS: {config.UNITS_BANNER}
! Mesh: {mesh}.inp     Applied axial strain: {strain}
! Expect peak stress on the order of E*strain = {expected:.0f} MPa, which is below the
! transformation start ({n['sigma_start_loading_MPa']:.0f} MPa).
! =====================================================================
FINISH
/CLEAR,NOSTART
/FILNAME,{out_stem},1          ! Self-naming within session
/TITLE, Bending verification

! ---- Mesh (defines ET, KEYOPT enhanced strain, nodes, elements)
/INPUT,'{mesh}','inp','{deck_dir}\\'

/PREP7
{material_card()}
ESEL,ALL
EMODIF,ALL,MAT,1               ! Bind the material to every imported element
FINISH

/SOLU
ANTYPE,STATIC
NLGEOM,ON
OUTRES,ALL,ALL
NSUBST,5,50,5

! ---- One end fixed, the other pulled a small amount along the tube axis
NSEL,ALL
*GET,ZMAX,NODE,0,MXLOC,Z
NSEL,S,LOC,Z,0
D,ALL,ALL,0
NSEL,S,LOC,Z,ZMAX
D,ALL,UZ,{strain}*ZMAX
NSEL,ALL
SOLVE
FINISH

/POST1
SET,LAST
NSORT,S,EQV
*GET,SMAXV,SORT,,MAX
NSORT,U,SUM
*GET,UMAXV,SORT,,MAX
*GET,NE,ELEM,0,COUNT
*GET,NN,NODE,0,COUNT
/OUTPUT,{out_stem},txt
*STATUS,NE
*STATUS,NN
*STATUS,SMAXV
*STATUS,UMAXV
/OUTPUT
FINISH
"""

def spike_a_loadsteps(mesh='spikeA_sector', deck_dir=None, radial_mm=0.01,
                      out_stem='s5_3_loadsteps', outres='ALL,ALL',
                      nsubst='20,200,10'):
    """
    Cyclic symmetry, radial stiffness, and a full axial compression cycle.

    No crimp in this step. S5.4's outputs don't need it, and what a crimp mainly
    adds is residual mean strain doesn't cap fatigue life.

    Ansys reports raw quantities only: imposed displacement, total reaction force, per-
    element strains. K_radial is computed in Python (sim3d/loadsteps.py), where it can be
    unit-tested against the 2D definition.

    LS1  radial displacement inward on the outer surface
    LS2  release
    LS3  axial compression to FLEX_AXIAL_COMPRESSION (walking, SFA - Poulson 2018)
    LS4  release, completing the cycle so a strain AMPLITUDE can be formed
    """
    deck_dir = (config.PROJECT_ROOT / 'sim3d' / 'decks') if deck_dir is None else deck_dir
    compression = config.FLEX_AXIAL_COMPRESSION
    r_outer = config.D_DEPLOYED_MM / 2.0 + config.STRUT_THICKNESS_MM

    return f"""! =====================================================================
! Cyclic symmetry + radial stiffness + axial compression cycle
! Generated by sim3d/apdl.py.
! UNITS: {config.UNITS_BANNER}
! Mesh: {mesh}.inp   Radial displacement: {radial_mm} mm   Axial compression: {compression}
! =====================================================================
FINISH
/CLEAR,NOSTART
/FILNAME,{out_stem},1          ! Self-naming within session
/TITLE, Radial stiffness and axial cycle

/INPUT,'{mesh}','inp','{deck_dir}\\'

/PREP7
{material_card()}
ESEL,ALL
EMODIF,ALL,MAT,1

CSYS,1                         ! Cylindrical: X radial, Y circumferential, Z axial
NSEL,ALL
NROTAT,ALL                     ! Rotate nodal DOFs to match

! ---- Cyclic symmetry: no circumferential motion on either cut face
NSEL,ALL
*GET,TMIN,NODE,0,MNLOC,Y
*GET,TMAX,NODE,0,MXLOC,Y
*GET,ZMAX,NODE,0,MXLOC,Z
NSEL,S,LOC,Y,TMIN
D,ALL,UY,0
NSEL,S,LOC,Y,TMAX
D,ALL,UY,0

! ---- Axial: one end fixed
NSEL,S,LOC,Z,0
D,ALL,UZ,0

! ---- The outer surface, which the radial load acts on
NSEL,ALL
NSEL,S,LOC,X,{r_outer}
CM,OUTER,NODE
*GET,NOUTER,NODE,0,COUNT
NSEL,ALL
/COM, ---- Cyclic symmetry faces at THETA = TMIN / TMAX, outer nodes = NOUTER
*STATUS,TMIN
*STATUS,TMAX
*STATUS,ZMAX
*STATUS,NOUTER
FINISH

/SOLU
ANTYPE,STATIC
NLGEOM,ON
LNSRCH,ON
AUTOTS,ON
OUTRES,{outres}
! MINREF: LS2 and LS4 return to zero load, where the reference force collapses and
! Newton-Raphson would otherwise check against an internal floor.
CNVTOL,F,,0.005,,1.0E-4
CNVTOL,U,,0.05,,1.0E-6

! ---- LS1: press the outer surface inward
CMSEL,S,OUTER
D,ALL,UX,-{radial_mm}
NSEL,ALL
NSUBST,{nsubst}
TIME,1
SOLVE

! ---- LS2: release
CMSEL,S,OUTER
DDELE,ALL,UX
NSEL,ALL
NSUBST,{nsubst}
TIME,2
SOLVE

! ---- LS3: axial compression (limb flexion, walking)
DAXIAL = -{compression}*ZMAX
NSEL,S,LOC,Z,ZMAX
D,ALL,UZ,DAXIAL
NSEL,ALL
NSUBST,{nsubst}
TIME,3
SOLVE

! ---- LS4: release, completing the cycle
NSEL,S,LOC,Z,ZMAX
D,ALL,UZ,0
NSEL,ALL
NSUBST,{nsubst}
TIME,4
SOLVE
FINISH

/POST1
! ---- Radial reaction at the end of LS1, while the displacement is still applied.
SET,1,LAST
CMSEL,S,OUTER
FSUM
*GET,FRADIAL,FSUM,0,ITEM,FX
NSEL,ALL

! Strain is read from nodal results, not ETABLE. Measured in s5_3_strain{{1..4}}: a
! centroidal ETABLE undersamples surface bending strain by (1-1/n) - 0.767 at 4 layers -
! because the element centroid sits inboard of the surface, where the strain is smaller.
! Nodal sampling reproduced the closed form exactly (1.000000) at every layer count.
SET,3,LAST
NSORT,EPTO,1,,1
*GET,EPS3,SORT,,MAX
SET,4,LAST
NSORT,EPTO,1,,1
*GET,EPS4,SORT,,MAX

SET,3,LAST
ETABLE,E3OLD,EPTO,1
ESORT,ETAB,E3OLD,,1
*GET,EPS3ETAB,SORT,,MAX
RATIO3 = EPS3ETAB/EPS3

! Amplitude has to be formed per location - differencing two global maxima subtracts
! values at different points, which is not an amplitude.
*GET,NMAXN,NODE,0,NUM,MAX
*DIM,A3,ARRAY,NMAXN
*DIM,A4,ARRAY,NMAXN
*DIM,AD,ARRAY,NMAXN
SET,3,LAST
*VGET,A3(1),NODE,1,EPTO,1
SET,4,LAST
*VGET,A4(1),NODE,1,EPTO,1
*VABS,1                        ! Absolute value of the result of the next vector operation
*VOPER,AD(1),A3(1),SUB,A4(1)
*VSCFUN,EPSRANGE,MAX,AD(1)
EPSAMP = 0.5*EPSRANGE

! ---- The whole per-node strain range field, for the volume-weighted A_over_lim.
/OUTPUT,{out_stem}_amp,txt
*VWRITE,AD(1)
(E16.8)
/OUTPUT

/OUTPUT,{out_stem},txt
*STATUS,NOUTER
*STATUS,ZMAX
*STATUS,DAXIAL
*STATUS,FRADIAL
*STATUS,EPS3
*STATUS,EPS4
*STATUS,EPS3ETAB
*STATUS,RATIO3
*STATUS,EPSRANGE
*STATUS,EPSAMP
/OUTPUT
FINISH

! ---- Time history across all four load steps.
/POST26
NUMVAR,20
CMSEL,S,OUTER
*GET,NOUT1,NODE,0,NUM,MIN
NSEL,ALL
NSEL,S,LOC,Z,ZMAX
*GET,NTOPZ,NODE,0,NUM,MIN
NSEL,ALL
NSOL,2,NOUT1,U,X
NSOL,3,NTOPZ,U,Z
RFORCE,4,NOUT1,F,X
RFORCE,5,NTOPZ,F,Z
/OUTPUT,{out_stem}_hist,txt
PRVAR,2,3,4,5
/OUTPUT
FINISH
"""

def spike_a_crimp(mesh='spikeA_fullring_L2', contact_inc='spikeA_contact_L2', deck_dir=None, stage_mm=4.0, out_stem='s5_3_crimp'):
    """
    Crimp to 2 mm with self-contact, deploy, then flex.

    Full ring, so there are no cut faces and no cyclic-symmetry constraints to get right.

    LS1  Crimp to `stage_mm`: sparse contact, a debugging checkpoint before the hard part
    LS2  Crimp to D_CRIMPED_MM: coverage ~0.74, self-contact fully engaged
    LS3  Release the crimper, spring back
    LS4  Axial compression (limb flexion, walking, SFA) on top of the crimp history
    LS5  Release, completing the cycle so an amplitude can be formed

    Load steps are ordered so a failure at LS2 still leaves LS1 usable in the .rst.
    """
    deck_dir = (config.PROJECT_ROOT / 'sim3d' / 'decks') if deck_dir is None else deck_dir
    compression = config.FLEX_AXIAL_COMPRESSION
    r_outer = config.D_DEPLOYED_MM / 2.0 + config.STRUT_THICKNESS_MM
    r_stage = stage_mm / 2.0
    r_final = config.D_CRIMPED_MM / 2.0

    return f"""! =====================================================================
! Crimp to {config.D_CRIMPED_MM} mm with self-contact, deploy, then flex
! Generated by sim3d/apdl.py.
! UNITS: {config.UNITS_BANNER}
! Mesh: {mesh}.inp   Contact: {contact_inc}.inp
! Crimper starts at RCRIMP0 and shrinks to {r_stage} then {r_final} mm.
! Coverage rises from f_metal 0.248 deployed to ~0.74 at {config.D_CRIMPED_MM} mm, so
! =====================================================================
FINISH
/CLEAR,NOSTART
/FILNAME,{out_stem},1          ! Self-naming within session
/TITLE, Crimp with self-contact, deploy, flex

/INPUT,'{mesh}','inp','{deck_dir}\\'
/INPUT,'{contact_inc}','inp','{deck_dir}\\'

/PREP7
{material_card()}

CSYS,1                         ! Cylindrical: X radial, Y circumferential, Z axial
NSEL,ALL
NROTAT,ALL

! ---- Stent base: axial anchor across the whole edge.
NSEL,S,LOC,Z,0
CMSEL,U,CRIMPN
D,ALL,UZ,0
CM,BASE,NODE
NSEL,ALL

! ---- Rigid-body control that does NOT fight the crimp.
! ---- Pinning UY across the whole base edge inverted elements at z~0.08 within 7 % of LS1:
! ---- crimping shrinks the circumference by 3x, and an edge pinned tangentially cannot
! ---- accommodate that. Three nodes 120 deg apart kill rigid rotation AND both in-plane
! ---- translations (rotation gives UY=const; x/y translation give UY=-d*sin/d*cos, and no
! ---- one of those vanishes at all three angles) while leaving the ring free to shrink.
! ---- NFIX1/2/3 come from the contact include file, resolved in Python. APDL angular
! ---- selection is fragile here: theta is stored on 0-360, so a range straddling zero
! ---- selects nothing, *GET returns 0, and D is silently ignored for node 0 to 0.
NSEL,ALL
D,NFIX1,UY,0
D,NFIX2,UY,0
D,NFIX3,UY,0

! ---- Crimper moves radially only.
CMSEL,S,CRIMPN
D,ALL,UY,0
D,ALL,UZ,0
NSEL,ALL

! ---- Reference node on the stent's outer skin, to track diameter.
NSEL,S,LOC,X,{r_outer}
CMSEL,U,CRIMPN
CM,OUTER,NODE
*GET,NOUT1,NODE,0,NUM,MIN
NSEL,ALL

NSEL,ALL
*GET,ZMAX,NODE,0,MXLOC,Z
DCRIMP1 = {r_stage}-RCRIMP0
DCRIMP2 = {r_final}-RCRIMP0
DAXIAL = -{compression}*ZMAX
/COM, ---- Crimper travel DCRIMP1 then DCRIMP2, axial DAXIAL, ref node NOUT1
*STATUS,RCRIMP0
*STATUS,DCRIMP1
*STATUS,DCRIMP2
*STATUS,ZMAX
*STATUS,NOUT1
*STATUS,NFIX1
*STATUS,NFIX2
*STATUS,NFIX3
FINISH

/SOLU
ANTYPE,STATIC
NLGEOM,ON
LNSRCH,ON
AUTOTS,ON
NEQIT,50                       ! Contact needs more equilibrium iterations than Part 1 did
OUTRES,ALL,LAST                ! Load-step ends only; ALL,ALL wrote a 1.9 GB .rst
CNVTOL,F,,0.005,,1.0E-4
CNVTOL,U,,0.05,,1.0E-6

! ---- LS1: crimp to {stage_mm} mm.
CMSEL,S,CRIMPN
D,ALL,UX,DCRIMP1
NSEL,ALL
NSUBST,50,500,20
TIME,1
SOLVE

! ---- LS2: crimp to {config.D_CRIMPED_MM} mm. Self-contact fully engaged.
CMSEL,S,CRIMPN
D,ALL,UX,DCRIMP2
NSEL,ALL
NSUBST,100,1000,40
TIME,2
SOLVE

! ---- LS3: release the crimper, spring back.
CMSEL,S,CRIMPN
D,ALL,UX,0
NSEL,ALL
NSUBST,50,500,20
TIME,3
SOLVE

! ---- LS4: axial compression on top of the crimp history.
NSEL,S,LOC,Z,ZMAX
CMSEL,U,CRIMPN
D,ALL,UZ,DAXIAL
NSEL,ALL
NSUBST,30,300,10
TIME,4
SOLVE

! ---- LS5: release, completing the cycle.
NSEL,S,LOC,Z,ZMAX
CMSEL,U,CRIMPN
D,ALL,UZ,0
NSEL,ALL
NSUBST,30,300,10
TIME,5
SOLVE
FINISH

/POST1
! ---- Proof that contact actually carried load.
SET,2,LAST
ESEL,S,TYPE,,3
ETABLE,CP1,CONT,PRES
ESORT,ETAB,CP1,,1
*GET,PCRIMP,SORT,,MAX
ESEL,S,TYPE,,5
ETABLE,SP1,CONT,PRES
ESORT,ETAB,SP1,,1
*GET,PSELF,SORT,,MAX
ESEL,ALL

! ---- Strain from NODAL results (s5_3_strain{{1..4}}: centroidal ETABLE undersamples).
NSORT,EPTO,1,,1
*GET,EPSCRIMP,SORT,,MAX
*GET,UCRIMP,NODE,NOUT1,U,X

SET,3,LAST
NSORT,EPTO,1,,1
*GET,EPSDEPLOY,SORT,,MAX
*GET,UDEPLOY,NODE,NOUT1,U,X
RDEPLOY = {r_outer}+UDEPLOY

SET,4,LAST
NSORT,EPTO,1,,1
*GET,EPS4,SORT,,MAX
SET,5,LAST
NSORT,EPTO,1,,1
*GET,EPS5,SORT,,MAX

! ---- Amplitude per location, by array math.
*GET,NMAXN,NODE,0,NUM,MAX
*DIM,A4,ARRAY,NMAXN
*DIM,A5,ARRAY,NMAXN
*DIM,AD,ARRAY,NMAXN
SET,4,LAST
*VGET,A4(1),NODE,1,EPTO,1
SET,5,LAST
*VGET,A5(1),NODE,1,EPTO,1
*VABS,1
*VOPER,AD(1),A4(1),SUB,A5(1)
*VSCFUN,EPSRANGE,MAX,AD(1)
EPSAMP = 0.5*EPSRANGE

/OUTPUT,{out_stem},txt
*STATUS,NE_ALL
*STATUS,NN_ALL
*STATUS,PCRIMP
*STATUS,PSELF
*STATUS,EPSCRIMP
*STATUS,UCRIMP
*STATUS,EPSDEPLOY
*STATUS,UDEPLOY
*STATUS,RDEPLOY
*STATUS,EPS4
*STATUS,EPS5
*STATUS,EPSRANGE
*STATUS,EPSAMP
/OUTPUT
FINISH
"""

def spike_a_crimp_post(results='s5_3_crimp', out_stem='s5_3_crimp_post'):
    """
    Read whatever load steps the crimp actually completed. No solve.

    OUTRES,ALL,LAST writes each load step's end as it finishes, so a run that dies partway
    still leaves usable results on disk. This resumes the database, attaches that results
    file, and walks every data set in it, so a crimp that reached LS1 but stalled in LS2
    still gives a real converged 4 mm crimp rather than nothing.

    Reports per data set: load step, time, peak nodal principal strain, crimper contact
    pressure, self-contact pressure, and the reference node's radial displacement.
    A set with zero contact pressure never actually touched, whatever else it reports.
    """
    r_outer = config.D_DEPLOYED_MM / 2.0 + config.STRUT_THICKNESS_MM
    return f"""! =====================================================================
! Post-process a crimp run without re-solving
! Generated by sim3d/apdl.py.
! UNITS: {config.UNITS_BANNER}
! Reads {results}.db + {results}.rst. Safe to run on a partial/failed solve.
! =====================================================================
FINISH
/CLEAR,NOSTART
/FILNAME,{out_stem},1          ! Own jobname, so the run's own files are not clobbered
RESUME,'{results}','db'

/POST1
FILE,'{results}','rst'
*GET,NSETS,ACTIVE,0,SET,NSET
/COM, ---- data sets found on the results file
*STATUS,NSETS

CSYS,1
NSEL,S,LOC,X,{r_outer}
CMSEL,U,CRIMPN
*GET,NOUT1,NODE,0,NUM,MIN
NSEL,ALL

*DIM,RES,ARRAY,NSETS,6
*DO,I,1,NSETS
  SET,,,,,,,I
  *GET,RES(I,1),ACTIVE,0,SET,LSTP
  *GET,RES(I,2),ACTIVE,0,SET,TIME
  NSEL,ALL
  NSORT,EPTO,1,,1
  *GET,RES(I,3),SORT,,MAX
  ETABLE,ERAS
  ESEL,S,TYPE,,3
  ETABLE,CPX,CONT,PRES
  ESORT,ETAB,CPX,,1
  *GET,RES(I,4),SORT,,MAX
  ETABLE,ERAS
  ESEL,S,TYPE,,5
  ETABLE,SPX,CONT,PRES
  ESORT,ETAB,SPX,,1
  *GET,RES(I,5),SORT,,MAX
  ESEL,ALL
  *GET,RES(I,6),NODE,NOUT1,U,X
*ENDDO

/OUTPUT,{out_stem},txt
*STATUS,NSETS
*STATUS,NOUT1
/COM,
/COM, LSTEP     TIME       EPS_MAX      P_CRIMPER      P_SELF         UR_OUTER
*VWRITE,RES(1,1),RES(1,2),RES(1,3),RES(1,4),RES(1,5),RES(1,6)
(F6.0,3X,F9.5,3X,E13.5,3X,E13.5,3X,E13.5,3X,E13.5)
/OUTPUT
FINISH
"""

# Decks this module can emit: filename -> builder.
def _strain_at(n):
    """Strain-sampling verification at n elements through the thickness."""
    def build():
        return bending_strain(n_through=n, out_stem=f's5_3_strain{n}')
    return build

def _bending_at(n):
    """Bending verification at n elements through the thickness, for the S5.3 layer sweep."""
    def build():
        return bending_verification(n_through=n, out_stem=f's5_3_layers{n}')
    return build

DECKS = {
    's0_2_spike_sma.inp': single_element_spike,
    's5_2_bending.inp': bending_verification,
    's5_2_model.inp': spike_a_model,
    's5_3_loadsteps.inp': spike_a_loadsteps,
    's5_3_layers1.inp': _bending_at(1),
    's5_3_layers2.inp': _bending_at(2),
    's5_3_layers3.inp': _bending_at(3),
    's5_3_layers4.inp': _bending_at(4),
    's5_3_strain1.inp': _strain_at(1),
    's5_3_strain2.inp': _strain_at(2),
    's5_3_strain3.inp': _strain_at(3),
    's5_3_strain4.inp': _strain_at(4),
    's5_3_crimp.inp': spike_a_crimp,
    's5_3_crimp_post.inp': spike_a_crimp_post,
}

DECK_DIR = config.PROJECT_ROOT / 'sim3d' / 'decks'

def write_decks(directory=None):
    """Write every deck in DECKS. Returns the paths written."""
    directory = DECK_DIR if directory is None else directory
    directory.mkdir(parents=True, exist_ok=True)
    written, locked = [], []
    for name, build in DECKS.items():
        path = directory / name
        try:
            path.write_text(build(), encoding='utf-8')
        except PermissionError:
            locked.append(path)
            continue
        written.append(path)
    return written, locked

if __name__ == "__main__":
    print(f'Generating from config.py  (E_A={config.NITINOL["E_austenite_MPa"]:.0f} MPa, '
          f'sigma_LS={config.NITINOL["sigma_start_loading_MPa"]:.0f} MPa, '
          f'alpha={alpha():.4f})')
    written, locked = write_decks()
    for path in written:
        print(f'  Wrote {path.relative_to(config.PROJECT_ROOT)}  '
              f'({path.stat().st_size} bytes)')
    for path in locked:
        print(f'  SKIPPED {path.relative_to(config.PROJECT_ROOT)} '
              f'- file is locked (Ansys still has it open)')
