"""
Generate Mechanical APDL input decks from config.

The material card is from config.NITINOL, so the numbers in Ansys can't drift from 
the sourced values in the repo.

Ansys superelasticity (TB,SMA,...,SUPE) takes six Auricchio constants:

    C1 sigma_s^AS   Start of the austenite -> martensite transformation (loading)
    C2 sigma_f^AS   Finish of it
    C3 sigma_s^SA   Start of the reverse transformation (unloading)
    C4 sigma_f^SA   Finish of it
    C5 epsilon_L    Maximum transformation strain
    C6 alpha        Tension/compression asymmetry

`alpha` is derived from the compressive transformation stress:
    alpha = (sigma_CLS - sigma_LS) / (sigma_CLS + sigma_LS)

The six-constant model carries one elastic modulus (austenite, via MP,EX). Our
E_martensite = 23500 MPa is therefore not used by this material card.
"""

import config

def alpha():
    """Tension/compression asymmetry parameter for the Auricchio model."""
    t = config.NITINOL['sigma_start_loading_MPa']
    c = config.NITINOL['sigma_start_loading_compression_MPa']
    return (c - t) / (c + t)

def material_card(mat=1):
    """APDL lines defining the superelastic nitinol material."""
    n = config.NITINOL
    return f"""! ---- Nitinol, superelastic (Auricchio). Generated from config.NITINOL.
! Source: {config.SOURCES['NITINOL'][:96]}...
MP,EX,{mat},{n['E_austenite_MPa']}          ! austenite Young's modulus, MPa
MP,PRXY,{mat},{n['poisson_austenite']}
MP,DENS,{mat},{n['density_tonne_per_mm3']}  ! tonne/mm^3 (mm-t-s system)
TB,SMA,{mat},,,SUPE
TBDATA,1,{n['sigma_start_loading_MPa']},{n['sigma_finish_loading_MPa']},\
{n['sigma_start_unloading_MPa']},{n['sigma_finish_unloading_MPa']},\
{n['eps_transformation']},{alpha():.6f}"""

def single_element_spike(strain=0.05, substeps=60, out_stem='sma_spike'):
    """
    One element, tension load-unload, dumping stress-strain to CSV.

    Displacement control, not force control - a superelastic plateau is flat in stress, so
    a force-driven test jumps straight across it and shows no hysteresis at all.
    """
    return f"""! =====================================================================
! Nitinol superelastic hysteresis, single element
! Generated by sim3d/apdl.py.
! UNITS: {config.UNITS_BANNER}
! Expect: loading plateau near {config.NITINOL['sigma_start_loading_MPa']:.0f}-\
{config.NITINOL['sigma_finish_loading_MPa']:.0f} MPa,
!         unloading plateau near {config.NITINOL['sigma_start_unloading_MPa']:.0f}-\
{config.NITINOL['sigma_finish_unloading_MPa']:.0f} MPa,
!         recoverable strain to ~{config.NITINOL['eps_transformation'] * 100:.1f} %,
!         and a closed loop returning to ~zero strain at zero stress.
! =====================================================================
FINISH
/CLEAR,NOSTART
/PREP7
/TITLE, S0.2 spike - nitinol superelasticity

ET,1,SOLID185                  ! 3D 8-node structural solid

{material_card()}

! ---- One 1 mm cube, so strain = displacement and stress = force
BLOCK,0,1,0,1,0,1
ESIZE,1
VMESH,ALL

! ---- Symmetry on three faces: uniaxial, free to contract laterally (Poisson)
NSEL,S,LOC,X,0
D,ALL,UX,0
NSEL,S,LOC,Y,0
D,ALL,UY,0
NSEL,S,LOC,Z,0
D,ALL,UZ,0
NSEL,ALL

! ---- Find the loaded node by location, not by assuming a node number
NSEL,S,LOC,Z,1
*GET,NTOP,NODE,0,NUM,MIN
NSEL,ALL
FINISH

/SOLU
ANTYPE,STATIC
NLGEOM,ON                      ! ~5 % strain is past the small-strain assumption
OUTRES,ALL,ALL
AUTOTS,ON

! ---- Load step 1: stretch to {strain * 100:.1f} %
NSEL,S,LOC,Z,1
D,ALL,UZ,{strain}
NSEL,ALL
NSUBST,{substeps},{substeps * 4},{substeps}
TIME,1
SOLVE

! ---- Load step 2: release back to zero
NSEL,S,LOC,Z,1
D,ALL,UZ,0
NSEL,ALL
NSUBST,{substeps},{substeps * 4},{substeps}
TIME,2
SOLVE
FINISH

! ---- Dump stress-strain history
! Strain is taken as UZ directly: the cube is 1 mm tall, so displacement is strain, and
! that sidesteps any ambiguity about which strain item Ansys reports under NLGEOM.
/POST26
NUMVAR,10
NSOL,2,NTOP,U,Z,UZ
ESOL,3,1,NTOP,S,Z,SZ
/OUTPUT,{out_stem},txt
PRVAR,2,3
/OUTPUT
! whitespace table, not true CSV - parse with sim3d.apdl.read_prvar()
FINISH
"""

def read_prvar(path):
    """
    Parse an APDL PRVAR table into (time, uz, sz) arrays.

    PRVAR writes a whitespace table with repeated headers and page breaks, not CSV, so this
    keeps only lines that are entirely numeric.
    """
    import numpy as np

    rows = []
    for line in open(path, encoding='utf-8', errors='ignore'):
        parts = line.split()
        if len(parts) < 3:
            continue
        try:
            rows.append([float(x) for x in parts[:3]])
        except ValueError:
            continue
    if not rows:
        raise ValueError(f'No numeric rows found in {path}')
    data = np.array(rows)
    return data[:, 0], data[:, 1], data[:, 2]

# Decks this module can emit: filename -> builder.
DECKS = {
    's0_2_spike_sma.inp': single_element_spike,
}

DECK_DIR = config.PROJECT_ROOT / 'sim3d' / 'decks'

def write_decks(directory=None):
    """Write every deck in DECKS. Returns the paths written."""
    directory = DECK_DIR if directory is None else directory
    directory.mkdir(parents=True, exist_ok=True)
    written = []
    for name, build in DECKS.items():
        path = directory / name
        path.write_text(build(), encoding='utf-8')
        written.append(path)
    return written

if __name__ == "__main__":
    print(f'Generating from config.py  (E_A={config.NITINOL["E_austenite_MPa"]:.0f} MPa, '
          f'sigma_LS={config.NITINOL["sigma_start_loading_MPa"]:.0f} MPa, '
          f'alpha={alpha():.4f})')
    for path in write_decks():
        print(f'  Wrote {path.relative_to(config.PROJECT_ROOT)}  '
              f'({path.stat().st_size} bytes)')
